Social_platform/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from user import urls as userurls
from posts import urls as posturls
from .views import profile
from connections import  urls as connectionurls


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', profile,name='home'),
    url(r'^user/', include(userurls, namespace='user')),
    url(r'^post/', include(posturls, namespace='post')),
    url(r'^connectionurl/', include(connectionurls, namespace='post')),

]

posts/urls.py
from django.conf.urls import url
from .views import PostCreate,PostDetailView,like

urlpatterns = [
    url(r'^createpost/$', PostCreate.as_view() , name='post'),
    # url(r'^feed/$', PostListView.as_view() , name='feed'),
    # url(r'add_like/$', add_like, name='add_like'),
    url(r'^feed/(?P<slug>[\w-]+)/$', PostDetailView.as_view() , name='detail'),
    url(r'^like/$', like, name='like'),
]

user/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import SignUp,updateinfo,Profile,LoginRedirect

urlpatterns = [
    url(r'^signup/', SignUp.as_view() , name='signup'),
    url(r'^redirect/$', LoginRedirect.as_view(), name='redirect'),
    url(r'^login/', auth_views.login, {'template_name':'login.html'} ,name='login'),
    url(r'^logout/', auth_views.logout, {'template_name':'logged_out.html'} ,name='logout'),
    url(r'^update/(?P<id>[0-9]+)/$', updateinfo, name='account_update'),
    url(r'^(?P<slug>[\-\w]+)/$', Profile.as_view(), name='profile'),

]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from autoslug import AutoSlugField


class UserProfile(models.Model):
    user = models.OneToOneField(User,related_name='user')
    bio = models.TextField(default='',blank=True)
    phone = models.CharField(max_length=13,blank=True,default='')
    city = models.TextField(max_length=50,blank=True,default='')
    slug = AutoSlugField(populate_from='user', unique=True)
    followers = models.ManyToManyField(User,null=True)

    def __str__(self):
        return f'{self.user}'


    def create_profile(sender,**kwargs):
        user = kwargs["instance"]
        if kwargs["created"]:
            user_profile = UserProfile(user=user)
            user_profile.save()

    post_save.connect(create_profile,sender=User)

user/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import UserProfile


class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        def save(self, commit=True):
            user = super(UserCreationForm, self).save(commit=False)
            user.email = self.cleaned_data['email']

            if commit:
                user.save()

            return user


# class UserForm(ModelForm):
#     class Meta:
#         model = User
#         fields = ['first_name','last_name','email']

user/views.py
from django.views import generic

# from .forms import UserForm
from django.forms.models import inlineformset_factory
from .forms import SignUpForm

from django.shortcuts import render, HttpResponseRedirect
from django.core.urlresolvers import reverse

from django.contrib.auth.models import User
from .models import UserProfile
from posts.models import Posts


from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import Http404
from django.shortcuts import render, get_object_or_404

# Create your views here.


class LoginRedirect(generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        user = self.request.user
        profile = UserProfile.objects.get(user=user)
        slug = profile.slug
        print(slug)
        return reverse('user:profile', kwargs={'slug':slug})





class SignUp(generic.CreateView):
    template_name = 'register.html'
    form_class = SignUpForm
    success_url = '/'


class Profile(LoginRequiredMixin,generic.DetailView):
    template_name = 'profile.html'

    def get_object(self):
        username = self.kwargs.get("slug")
        if username is None:
            raise Http404
        obj=get_object_or_404(UserProfile,slug=username)
        print(obj)
        return obj

    def get_context_data(self, **kwargs):
        context = super(Profile, self).get_context_data(**kwargs)
        context["posts"] = Posts.objects.filter(created_by=self.request.user)
        return context

# @login_required() # only logged in users should access this
# def edit_user(request,pk):
#     # querying the User object with pk from url
#     # pk = request.user.pk
#     user = User.objects.get(pk=pk)
#
#     # prepopulate UserProfileForm with retrieved user values from above.
#     user_form = UserForm(instance=user)
#
#     # The sorcery begins from here, see explanation below
#     ProfileInlineFormset = inlineformset_factory(User, UserProfile, fields=('bio', 'phone', 'city'))
#     formset = ProfileInlineFormset(instance=user)
#
#     if request.user.is_authenticated() and request.user.id == user.id:
#         if request.method == "POST":
#             user_form = UserForm(request.POST, request.FILES, instance=user)
#             formset = ProfileInlineFormset(request.POST, request.FILES, instance=user)
#
#             if user_form.is_valid():
#                 created_user = user_form.save(commit=False)
#                 formset = ProfileInlineFormset(request.POST, request.FILES, instance=created_user)
#
#                 if formset.is_valid():
#                     created_user.save()
#                     formset.save()
#                     return HttpResponseRedirect('/accounts/profile/')
#
#         return render(request, "account_update.html", {
#             "noodle": pk,
#             "noodle_form": user_form,
#             "formset": formset,
#         })
#     else:
#         raise PermissionDenied
# @login_required() # only logged in users should access this
# def edit_user(request):
#     # querying the User object with pk from url
#     # pk = request.user.pk
#     user = request.user
#
    # profile = UserProfile.objects.get(user=user)
    # slug = profile.slug
#
#     # prepopulate UserProfileForm with retrieved user values from above.
#     user_form = UserForm(instance=user)
#
#     # The sorcery begins from here, see explanation below
#     ProfileInlineFormset = inlineformset_factory(User, UserProfile, fields=('bio', 'phone', 'city'))
#     formset = ProfileInlineFormset(instance=user)
#
#     if request.user.is_authenticated() and request.user.id == user.id:
#         if request.method == "POST":
#             user_form = UserForm(request.POST, request.FILES, instance=user)
#             formset = ProfileInlineFormset(request.POST, request.FILES, instance=user)
#
#             if user_form.is_valid():
#                 created_user = user_form.save(commit=False)
#                 formset = ProfileInlineFormset(request.POST, request.FILES, instance=created_user)
#
#                 if formset.is_valid():
#                     created_user.save()
#                     formset.save()
#                     return reverse('user:profile', kwargs={'slug':slug})
#
        # return render(request, "account_update.html", {
        #     "noodle": slug,
        #     "noodle_form": user_form,
        #     "formset": formset,
        # })
#     else:
#         raise PermissionDenied

@login_required()
def updateinfo(request,id):

    user = User.objects.get(id=id)

    profile = UserProfile.objects.get(user=user)
    slug = profile.slug

    ProfileInlineFormset = inlineformset_factory(User, UserProfile, fields=('bio', 'phone', 'city'))
    formset = ProfileInlineFormset(instance=user)

    if request.user.is_authenticated() and request.user.id == user.id:
        if request.method == 'POST':
            formset = ProfileInlineFormset(request.POST, request.FILES, instance=user)

            if formset.is_valid():
                formset.save()
                return HttpResponseRedirect(reverse('user:profile', kwargs={'slug':slug}))

        return render(request, "account_update.html", {
            "noodle": slug,
            "formset": formset,
        })

user/templates/account_update.html
{% extends 'base.html' %}
{#{% load material_form %}#}
{#<!-- Material form is just a materialize thing for django forms -->#}
{#{% block content %}#}
{#<div>#}
{#          <form action="." method="POST" class="padding">#}
{#            {% csrf_token %} {{ noodle_form.as_p }}#}
{#            <div class="divider"></div>#}
{#            {{ formset.management_form }}#}
{#          {% form form=formset.management_form %}{% endform %}#}
{#                {{ formset.as_p }}#}
{#              {% form form=formset %}#}
{#              {% endform %}#}
{#            <button type="submit">done</></button>#}
{#        </form>#}
{#        </div>#}
{#    </div>#}
{#</div>#}
{#{% endblock %}#}


{% load material_form %}
<!-- Material form is just a materialize thing for django forms -->

{% block content %}
<div class="col s12 m8 offset-m2">
      <div class="card">
        <div class="card-content">
        <h2 class="flow-text">Update your information</h2>
          <form action="" method="POST" class="padding">
            {% csrf_token %}
            <div class="divider"></div>
            {{ formset.management_form }}
                {{ formset.as_p }}
              <input type="submit" value="update">
        </form>
        </div>
    </div>
</div>
{% endblock %}

user/templates/logged_out.html
{% extends 'base.html' %}

{% block title %}
    Successfully logged out || {{ block.super }}
{% endblock %}

{% block content %}
    <div class="col-md-4">
    <p>Come back soon</p>
    <a href="{% url 'user:login' %}">Login</a>
    </div>
{% endblock %}

user/templates/login.html
{#{% extends "base.html" %}#}



{#{% block content %}#}
{##}
{#    <form method="post" action="">{% csrf_token %}#}
{#         {% form form=form %}{% endform %}#}
{#        <input type="submit" value="Signin">#}
{#    </form>#}
{% extends 'base.html' %}
{% load static %}
{% load material_form %}



{% load static %}
{% load material_form %}

{% block title %}
    {{ block.super }} | Login
{% endblock %}

{% block content %}
    <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
<div class="container bootstrap snippet">
    <div class="row login-page">
        <div class="col-md-4 col-lg-4 col-md-offset-4 col-lg-offset-4">
    		<img src="http://ani-theme.strapui.com/images/flat-avatar.png" class="user-avatar">
    		<h1>Bootdey.com</h1>
    		    <form method="post" action="">{% csrf_token %}
         {% form form=form %}{% endform %}
        <input type="submit" value="Signin">
    </form>
    	</div>
    </div>
</div>
</body>
{% endblock %}

user/templates/profile.html
{#{% extends 'base.html' %}#}
{##}
{#{% block content %}#}
{##}
{#    #}
{#    <div>#}
{#        <div>#}
{#        {{ object.user }}#}
{#        {{ object.bio }}#}
{#        {{ object.phone }}#}
{#    {{ object.city }}#}
{#    </div>#}
{#{% endblock %}#}

{% extends 'base.html' %}
{% load static %}

{% block title %}

{% endblock %}

{% block head %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/userprofile.css' %}">
{% endblock %}

{% block content %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <div class="container">
    <div class="row">
        <div class="col-sm-8 col-sm-offset-2">
            <div class="panel panel-white profile-widget">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="image-container bg2" style="background:url(http://www.bootdey.com/img/Content/flores-amarillas-wallpaper.jpeg)">
                            <img src="https://bootdey.com/img/Content/avatar/avatar6.png" class="avatar" alt="avatar">
                        </div>
                    </div>
                    <div class="col-sm-12">
                        <div class="details">
                            <h4>{{ object.user }}<i class="fa fa-sheild"></i></h4>
                            <div>Bio {{ object.bio }}</div>
                            <div>Contact number {{ object.phone }}</div>
                            <div>Lives in {{ object.city }}</div>
                            <div class="mg-top-10">
                                <a href="{% url 'user:account_update' id=request.user.id %}" class="btn btn-default">Update Info</a>
                                <a href="{% url 'post:post' %}" class="btn btn-success">Add Post</a>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

            </div>

        </div>


    </div>
</div>
{% endblock %}

user/templates/register.html
{#{% extends "base.html" %}#}
{#{% load material_form %}#}
{##}
{#{% block content %}#}
{##}
{#    <form method="post" action="">{% csrf_token %}#}
{#         {% form form=form %}{% endform %}#}
{#        <input type="submit" value="SignUp">#}
{#    </form>#}
{##}
{#{% endblock %}#}

{% load static %}
{% load material_form %}
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
            {% include 'material/includes/material_css.html' %}
</head>
<body>
<div class="container bootstrap snippet">
    <div class="row login-page">
        <div class="col-md-4 col-lg-4 col-md-offset-4 col-lg-offset-4">
    		<img src="http://ani-theme.strapui.com/images/flat-avatar.png" class="user-avatar">
    		<h1>Bootdey.com</h1>
        <form method="post" action="">{% csrf_token %}
             {% form form=form %}{% endform %}
            <input type="submit" value="SignUp">
        </form>
    	</div>
    </div>
</div>
</body>

  <script src="{% static 'material/js/jquery.js' %}"></script>
      {% include 'material/includes/material_js.html' %}